/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef EX2_DBC
#define EX2_DBC

#include <stdint.h>


#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

typedef PREPACK struct {
	float Torque; /* scaling 1.0, offset 0.0, units Nm , floating */
	float Speed; /* scaling 1.0, offset 0.0, units MPH , floating */
} POSTPACK can_0x064_DynLoc_t;

typedef PREPACK struct {
	float DynoMCNMotorTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3df_DynoMotorTemp_t;

typedef PREPACK struct {
	float DynoMCNAmbientTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e0_DynoAmbientTemp_t;

typedef PREPACK struct {
	float DynoMotorPlateTemp2; /* scaling 1.0, offset 0.0, units none , floating */
	float DynoMotorPlateTemp1; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e1_DynoMotorPlateTemps_t;

typedef PREPACK struct {
	float CoolantFlow; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e2_DynoCoolantFlow_t;

typedef PREPACK struct {
	float MotorCoolantTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e3_DynoMotorCoolantTemp_t;

typedef PREPACK struct {
	float MotorControllerCoolantTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e4_DynoMotorControllerCoolantTemp_t;

typedef PREPACK struct {
	float RadiatorCoolantTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e5_DynoRadiatorCoolantTemp_t;

typedef PREPACK struct {
	float CoolantPressure2; /* scaling 1.0, offset 0.0, units none , floating */
	float CoolantPressure1; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x3e6_DynoCoolantPressures_t;

typedef PREPACK struct {
	uint32_t DynoMCNUserFlags; /* scaling 1.0, offset 0.0, units none  */
	uint32_t DynoMCNSystemFlags; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x3e7_DynoMCNStatus_t;

typedef PREPACK struct {
	uint32_t SerialNumber; /* scaling 1.0, offset 0.0, units none  */
	uint32_t TritiumID; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x400_WS200IDInfo_t;

typedef PREPACK struct {
	uint16_t ErrorFlags; /* scaling 1.0, offset 0.0, units none  */
	uint16_t ActiveMotor; /* scaling 1.0, offset 0.0, units none  */
	uint16_t LimitFlags; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ReceiveErrorCount; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TransmitErrorCount; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x401_WS200Status_t;

typedef PREPACK struct {
	float BusCurrent; /* scaling 1.0, offset 0.0, units none , floating */
	float BusVoltage; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x402_WS200BusMeasurement_t;

typedef PREPACK struct {
	float VehicleVelocity; /* scaling 1.0, offset 0.0, units none , floating */
	float MotorVelocity; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x403_VelocityMeasurement_t;

typedef PREPACK struct {
	float PhaseCurrentC; /* scaling 1.0, offset 0.0, units none , floating */
	float PhaseCurrentB; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x404_PhaseCurrent_t;

typedef PREPACK struct {
	float Vd; /* scaling 1.0, offset 0.0, units none , floating */
	float Vq; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x405_MotorVoltage_t;

typedef PREPACK struct {
	float Id; /* scaling 1.0, offset 0.0, units none , floating */
	float Iq; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x406_MotorCurrent_t;

typedef PREPACK struct {
	float BEMFd; /* scaling 1.0, offset 0.0, units none , floating */
	float BEMFq; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x407_MotorBackEMF_t;

typedef PREPACK struct {
	float Supply15V; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x408_WS200Rail15V_t;

typedef PREPACK struct {
	float Rail3V; /* scaling 1.0, offset 0.0, units none , floating */
	float Rail2V; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x409_WS200LowRail_t;

typedef PREPACK struct {
	float IPMPhaseATemp; /* scaling 1.0, offset 0.0, units none , floating */
	float MotorTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x40b_WS200MotorTemp_t;

typedef PREPACK struct {
	float DSPBoardTemp; /* scaling 1.0, offset 0.0, units none , floating */
	float IPMPhaseBTemp; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x40c_WS200DSPBoardTemp_t;

typedef PREPACK struct {
	float IMPPhaseCTemp; /* scaling 1.0, offset 0.0, units none , floating */
	float Reserved; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x40d_WS200PhaseCTemp_t;

typedef PREPACK struct {
	float DCBusAmpHours; /* scaling 1.0, offset 0.0, units none , floating */
	float Odometer; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x40e_WS200BusAmpHours_t;

typedef PREPACK struct {
	float Reserved; /* scaling 1.0, offset 0.0, units none , floating */
	float SlipSpeed; /* scaling 1.0, offset 0.0, units none , floating */
} POSTPACK can_0x417_WS200SlipSpeed_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x064_DynLoc_time_stamp_rx;
	dbcc_time_stamp_t can_0x3df_DynoMotorTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e0_DynoAmbientTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e1_DynoMotorPlateTemps_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e2_DynoCoolantFlow_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e3_DynoMotorCoolantTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e4_DynoMotorControllerCoolantTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e5_DynoRadiatorCoolantTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e6_DynoCoolantPressures_time_stamp_rx;
	dbcc_time_stamp_t can_0x3e7_DynoMCNStatus_time_stamp_rx;
	dbcc_time_stamp_t can_0x400_WS200IDInfo_time_stamp_rx;
	dbcc_time_stamp_t can_0x401_WS200Status_time_stamp_rx;
	dbcc_time_stamp_t can_0x402_WS200BusMeasurement_time_stamp_rx;
	dbcc_time_stamp_t can_0x403_VelocityMeasurement_time_stamp_rx;
	dbcc_time_stamp_t can_0x404_PhaseCurrent_time_stamp_rx;
	dbcc_time_stamp_t can_0x405_MotorVoltage_time_stamp_rx;
	dbcc_time_stamp_t can_0x406_MotorCurrent_time_stamp_rx;
	dbcc_time_stamp_t can_0x407_MotorBackEMF_time_stamp_rx;
	dbcc_time_stamp_t can_0x408_WS200Rail15V_time_stamp_rx;
	dbcc_time_stamp_t can_0x409_WS200LowRail_time_stamp_rx;
	dbcc_time_stamp_t can_0x40b_WS200MotorTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x40c_WS200DSPBoardTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x40d_WS200PhaseCTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x40e_WS200BusAmpHours_time_stamp_rx;
	dbcc_time_stamp_t can_0x417_WS200SlipSpeed_time_stamp_rx;
	unsigned can_0x064_DynLoc_status : 2;
	unsigned can_0x064_DynLoc_tx : 1;
	unsigned can_0x064_DynLoc_rx : 1;
	unsigned can_0x3df_DynoMotorTemp_status : 2;
	unsigned can_0x3df_DynoMotorTemp_tx : 1;
	unsigned can_0x3df_DynoMotorTemp_rx : 1;
	unsigned can_0x3e0_DynoAmbientTemp_status : 2;
	unsigned can_0x3e0_DynoAmbientTemp_tx : 1;
	unsigned can_0x3e0_DynoAmbientTemp_rx : 1;
	unsigned can_0x3e1_DynoMotorPlateTemps_status : 2;
	unsigned can_0x3e1_DynoMotorPlateTemps_tx : 1;
	unsigned can_0x3e1_DynoMotorPlateTemps_rx : 1;
	unsigned can_0x3e2_DynoCoolantFlow_status : 2;
	unsigned can_0x3e2_DynoCoolantFlow_tx : 1;
	unsigned can_0x3e2_DynoCoolantFlow_rx : 1;
	unsigned can_0x3e3_DynoMotorCoolantTemp_status : 2;
	unsigned can_0x3e3_DynoMotorCoolantTemp_tx : 1;
	unsigned can_0x3e3_DynoMotorCoolantTemp_rx : 1;
	unsigned can_0x3e4_DynoMotorControllerCoolantTemp_status : 2;
	unsigned can_0x3e4_DynoMotorControllerCoolantTemp_tx : 1;
	unsigned can_0x3e4_DynoMotorControllerCoolantTemp_rx : 1;
	unsigned can_0x3e5_DynoRadiatorCoolantTemp_status : 2;
	unsigned can_0x3e5_DynoRadiatorCoolantTemp_tx : 1;
	unsigned can_0x3e5_DynoRadiatorCoolantTemp_rx : 1;
	unsigned can_0x3e6_DynoCoolantPressures_status : 2;
	unsigned can_0x3e6_DynoCoolantPressures_tx : 1;
	unsigned can_0x3e6_DynoCoolantPressures_rx : 1;
	unsigned can_0x3e7_DynoMCNStatus_status : 2;
	unsigned can_0x3e7_DynoMCNStatus_tx : 1;
	unsigned can_0x3e7_DynoMCNStatus_rx : 1;
	unsigned can_0x400_WS200IDInfo_status : 2;
	unsigned can_0x400_WS200IDInfo_tx : 1;
	unsigned can_0x400_WS200IDInfo_rx : 1;
	unsigned can_0x401_WS200Status_status : 2;
	unsigned can_0x401_WS200Status_tx : 1;
	unsigned can_0x401_WS200Status_rx : 1;
	unsigned can_0x402_WS200BusMeasurement_status : 2;
	unsigned can_0x402_WS200BusMeasurement_tx : 1;
	unsigned can_0x402_WS200BusMeasurement_rx : 1;
	unsigned can_0x403_VelocityMeasurement_status : 2;
	unsigned can_0x403_VelocityMeasurement_tx : 1;
	unsigned can_0x403_VelocityMeasurement_rx : 1;
	unsigned can_0x404_PhaseCurrent_status : 2;
	unsigned can_0x404_PhaseCurrent_tx : 1;
	unsigned can_0x404_PhaseCurrent_rx : 1;
	unsigned can_0x405_MotorVoltage_status : 2;
	unsigned can_0x405_MotorVoltage_tx : 1;
	unsigned can_0x405_MotorVoltage_rx : 1;
	unsigned can_0x406_MotorCurrent_status : 2;
	unsigned can_0x406_MotorCurrent_tx : 1;
	unsigned can_0x406_MotorCurrent_rx : 1;
	unsigned can_0x407_MotorBackEMF_status : 2;
	unsigned can_0x407_MotorBackEMF_tx : 1;
	unsigned can_0x407_MotorBackEMF_rx : 1;
	unsigned can_0x408_WS200Rail15V_status : 2;
	unsigned can_0x408_WS200Rail15V_tx : 1;
	unsigned can_0x408_WS200Rail15V_rx : 1;
	unsigned can_0x409_WS200LowRail_status : 2;
	unsigned can_0x409_WS200LowRail_tx : 1;
	unsigned can_0x409_WS200LowRail_rx : 1;
	unsigned can_0x40b_WS200MotorTemp_status : 2;
	unsigned can_0x40b_WS200MotorTemp_tx : 1;
	unsigned can_0x40b_WS200MotorTemp_rx : 1;
	unsigned can_0x40c_WS200DSPBoardTemp_status : 2;
	unsigned can_0x40c_WS200DSPBoardTemp_tx : 1;
	unsigned can_0x40c_WS200DSPBoardTemp_rx : 1;
	unsigned can_0x40d_WS200PhaseCTemp_status : 2;
	unsigned can_0x40d_WS200PhaseCTemp_tx : 1;
	unsigned can_0x40d_WS200PhaseCTemp_rx : 1;
	unsigned can_0x40e_WS200BusAmpHours_status : 2;
	unsigned can_0x40e_WS200BusAmpHours_tx : 1;
	unsigned can_0x40e_WS200BusAmpHours_rx : 1;
	unsigned can_0x417_WS200SlipSpeed_status : 2;
	unsigned can_0x417_WS200SlipSpeed_tx : 1;
	unsigned can_0x417_WS200SlipSpeed_rx : 1;
	can_0x064_DynLoc_t can_0x064_DynLoc;
	can_0x3df_DynoMotorTemp_t can_0x3df_DynoMotorTemp;
	can_0x3e0_DynoAmbientTemp_t can_0x3e0_DynoAmbientTemp;
	can_0x3e1_DynoMotorPlateTemps_t can_0x3e1_DynoMotorPlateTemps;
	can_0x3e2_DynoCoolantFlow_t can_0x3e2_DynoCoolantFlow;
	can_0x3e3_DynoMotorCoolantTemp_t can_0x3e3_DynoMotorCoolantTemp;
	can_0x3e4_DynoMotorControllerCoolantTemp_t can_0x3e4_DynoMotorControllerCoolantTemp;
	can_0x3e5_DynoRadiatorCoolantTemp_t can_0x3e5_DynoRadiatorCoolantTemp;
	can_0x3e6_DynoCoolantPressures_t can_0x3e6_DynoCoolantPressures;
	can_0x3e7_DynoMCNStatus_t can_0x3e7_DynoMCNStatus;
	can_0x400_WS200IDInfo_t can_0x400_WS200IDInfo;
	can_0x401_WS200Status_t can_0x401_WS200Status;
	can_0x402_WS200BusMeasurement_t can_0x402_WS200BusMeasurement;
	can_0x403_VelocityMeasurement_t can_0x403_VelocityMeasurement;
	can_0x404_PhaseCurrent_t can_0x404_PhaseCurrent;
	can_0x405_MotorVoltage_t can_0x405_MotorVoltage;
	can_0x406_MotorCurrent_t can_0x406_MotorCurrent;
	can_0x407_MotorBackEMF_t can_0x407_MotorBackEMF;
	can_0x408_WS200Rail15V_t can_0x408_WS200Rail15V;
	can_0x409_WS200LowRail_t can_0x409_WS200LowRail;
	can_0x40b_WS200MotorTemp_t can_0x40b_WS200MotorTemp;
	can_0x40c_WS200DSPBoardTemp_t can_0x40c_WS200DSPBoardTemp;
	can_0x40d_WS200PhaseCTemp_t can_0x40d_WS200PhaseCTemp;
	can_0x40e_WS200BusAmpHours_t can_0x40e_WS200BusAmpHours;
	can_0x417_WS200SlipSpeed_t can_0x417_WS200SlipSpeed;
} POSTPACK can_obj_ex2_dbc_t;




















































#ifdef __cplusplus
} 
#endif

#endif
